### ISSUE TITLE
No delivery to recipients with no key. 

### ISSUE THREAD

**Issue by TinkerFu** [ajgon/gpg-mailgate.py#2]
If there is no key present for the intended recipient then the message is not delivered.  Last message in log is postfix handing it to gpg-mailgate. 

Delivery works fine if there is a key present for the intended recipient. 

Running postfix, dovecot.  Was running uakfdotb's fork of this but no attachment support.

**Comment by ajgon** [comment]
I included @uakfdotb commit 527f123391a0c3b273f4dd02a04eb0dd49620e9f in branch. Was it the one fixing this issue?

**Comment by uakfdotb** [comment]
I think that's the right one, or at least one of two-three relating to delivery issues. Does your branch handle attachments properly? Because my gpg-mailgate is hit-or-miss, sometimes it works (usually?), but sometimes it doesn't.

**Comment by TinkerFu** [comment]
I don't have a fork but I actually combined all these forks into a single fully working script.  Not sure what to do with it though.

**Comment by ajgon** [comment]
Hey guys, I'm on my vacation now (yeah, online :smile:), I'll be back at the end of the month, and I plan to do a heavy testing of it and make it as reliable as possible. 
If you have any log files of not workinng cases, comments or ideas you can share, please don't hesitate to, your help is very appreciated. @uakfdotb thanks for all the patches as well!

**Comment by uakfdotb** [comment]
I think I've fixed the attachment by setting the transfer encoding to 7bit. Originally I set it to quoted-printable, which fixed some attachments but messed up others.

**Comment by TinkerFu** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Just thought I'd share,  I have attachments working.  Well it seems to work,  I've not run into issues yet.

Thanks
Bruce

uakfdotb notifications@github.com wrote:

> -----BEGIN PGP MESSAGE-----
> Version: GnuPG v1.4.14 (GNU/Linux)
> 
> hQIMAydDBqzdFhNTAQ/+MNTnFRe1XBMMSj5nC4gSivZz3JH1JRnaFZ1zko+Kj1p2
> 0hqPf0M6iunQXznThwDPW3AIJkEkAdHgTEaWBCd/f501I7Tx/Udbqkbb+RvRg9rr
> P3Dw58tOvK88w2QhJWOzznjw8FqZxKfuUP7DBNTjd5cTRecJN1S5egIgxU5+Iv/F
> tdgOrcs40k66OClI3RRT8+udlU/4eNDGoD/IamNEq4ZsNDB6XSeUKjtRD11TTQZq
> wq4kls9OlfHJwoAD3QeFAIk/WJlvrZi2b0kt3QEsqkleIxvvUNrtJT0bdN9RQsT3
> mfDyjIQ2XOJda3GydoAh2u9v1pOu1SdYYaDsDO8Zj2yGAjQfbqfBpzjqUMndN6sA
> FgFQ7kLE9DSuRx7AxiPyJyOTm6EBUp3bLT/UgQocNakwCPk0v/E4qpAldwmKYzqx
> ZGNRdIPALr14fK5UqryCHvMqCikfFRHCVXpCl10jg++VWrtpPVyEITwim4lrWWiJ
> X4Gwd/PIdDKpYYP7eIce7rcZtZaxK0h8VsgcpC1r1g5reN1/hZsjyzLqtrUBsbA+
> 3zczMxFPG1+cJJIayQ8KTpW2XXJPAiRTvG0DRhX1xhvqwwg23Hv0wrSTPt3YxPSy
> Cg2dsR0kMiNxP0M7+GE2IFnY3zz50pO6arhxfMu2snoYq229ll/9gdj4b8qKrifS
> wEsBYt0zOAd4JXKRKyVi5nrNHSwElJHIhtUjfBTmH8dEHY5vhAcLD2D6WPsdVHaU
> dRoH6/nbsRcXgpyCAMvV/fzzpdUi53qAMXhF6FoKbvz1vh3SazPYOZBOJ6eHyqLd
> IVMJvzgmTbwi1+fX/g7e9lJXXGN8r3Hq8vATAdx05fOrANftbwz+G3yjuAtYOitg
> nhN3lWHPUQveckwMIP6+iT+bVN9fGi1xDcj0PNt0golwm4C3T0Ng7PD/Zbjx0lip
> 9QdUylL1CHtGJZWIJtkDH3YXHQxaSGLcdEU4MsNec7ay7T/clDVcxBiUvVgWEd1K
> +c9B6D7o+xn0uG0Tv3sQVvwFyQblXSinvx3MC9Q=
> =Pw6a
> -----END PGP MESSAGE-----

---

Sent from my Android device with K-9 Mail. Please excuse my brevity.
-----BEGIN PGP SIGNATURE-----
Version: APG v1.0.8

iQJSBAEBCAA8BQJSP05jNRxCcnVjZSBNYXJrZXkgKFNlY3J5cHRpb24uY29tKSA8
YnJ1Y2VAc2VjcnlwdGlvbi5jb20+AAoJEMhVxLguBzpYgswP/iCYeA7LvbBpJXOq
B7oyWnd9rkrdEZyyf9iwZqTztXFuDRCw0htxpqZtG0kV3piPFXeqbR/Ac90oBevo
QlGtNLWuQDOr0dRbLUEDn11tbDlDnawSLFR4l11IXFfIOkXxPfq9740BkYXH50hb
C4jyWdBptRDo5qOPzdOKWGEPNFnzU4H/LlO587X7Q46hPGZ/mr1iR81PhQ/+DwSh
6JmYswIr0GRuffaKl9rxG9JmCWL1KBsKCqoeCvsQfA/pvLH0D8t0ISaFT2bF4rGo
9oGg+kV2Bz16qaKfimHx1XGR6Cuizjun0RR4nUZCDFBQB3vN9eDuxFChoApMcXbV
Wi+HSgXGQCAhEKug5oCp7UDz3Td6QTk9VHfqS5VSaxo6M1+p3BPrPq2mxMJb2qkk
cD5uk5JvLqPwLekqd3rBSVgHP+MFzcaKqQVJpkFOwXdzXVq6G5dWNnnBugS1rQbK
5Br/klnFnZKNX4MttcF371YaGYUtOiZXXKF79jvTtMHsObQXPbPlskOtYoDNm4Q1
v6rDPAZvtzmqxpEWFwm3TaSZ1pG4V/YSkjPSVThvUoGdPgsVJN6heaSbSe0xR8bF
giLOJpzk3qZsNo2two2G7g5lFMETGcqNj9bm77eFZ3D/dqTVMjuSdCB+nAi5GkDi
DGLRG+ij+4aY5t4aVxoo+l9sd/vY
=02DW
-----END PGP SIGNATURE-----

**Comment by ajgon** [comment]
Merged.
