### ISSUE TITLE
Base64 encoding produces garbled output. 

### ISSUE THREAD

**Issue by TinkerFu** [ajgon/gpg-mailgate.py#4]
I only notice this from a few odd clients but when the headers are:
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
MIME-Version: 1.0

The resulting message is garbled garbage.   It seems to come from Exchange servers mostly.

**Comment by uakfdotb** [comment]
I believe this was fixed a while ago in my fork or the unstable branch.
